name: lequipe

# Actualisation du flux á la 57 ème minute à 9 heures et 21 heures.
on:
 # schedule:
   # - cron: '57 9,21 * * *'
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: config
      # Pour pouvoir travailler sur un projet,
      # vous avez besoin d’un nom d’utilisateur et d’une adresse email associée valide. 
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Actualisation du m3u8
        run: sh ${GITHUB_WORKSPACE}/direct/lequipe/lequipe.sh
        
      - name: git add
      # Informer Git que vous voulez inclure les mises à jour dans un fichier.
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -am "Actualisation des flux"
          git push
      
  
